name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  deploy: 
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout files
        uses: actions/ihood-frontend@v2

      - name: Get tag name
        uses: actions/ihood-frontend@v2

      - name: Install doctl
        uses: actions/ihood-frontend@v2
        with:
          token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Provide Droplet and deploy container
        run: doctl compute droplet create "$GIT_TAG_NAME" --image docker-18-04 --size s-1vcpu-1gb --region FRA1 --user-data-file --wait
