name: Frontend CI/CD
  
on:
  push:
     branches:
      - main
  pull_request:
      branches:
      - main
  
jobs:
  build:
  
    runs-on: ubuntu-latest
 
    steps:
      - uses: fullstacktf/ihood-frontend@v1
      - name: Install & Tests
        run: |
          npm install
          npm run test
  
  deploy: 
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout files
        uses: fullstacktf/ihood-frontend@v2

      - name: Get tag name
        uses: fullstacktf/ihood-frontend@v2

      - name: Install doctl
        uses: fullstacktf/ihood-frontend@v2
        with:
          token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Provide Droplet and deploy container
        run: doctl compute droplet create "$GIT_TAG_NAME" --image docker-18-04 --size s-1vcpu-1gb --region FRA1 --user-data-file --wait
